services:
  app:
    build: .
    image: random-pass_img
    volumes:
      - ./app:/app
    working_dir: /app
    container_name: "random-pass_ctn"
    hostname: "random-pass"
    ports:
      - 1234:1234
    entrypoint: [ "yarn", "dev" ]
    # entrypoint: [ "sh", "-c", "sleep 2073600" ]
