version: "3.7"

services:
  app:
    build: .
    image: random-pass_img
    volumes:
      - .:/app
    working_dir: /app
    container_name: "random-pass_ctn"
    hostname: "random-pass"
    ports:
      - 8080:8080
    entrypoint: ["yarn", "serve"]
